sheduler:
  serviceAccountName: mongo-scheduler-sa
  image: "oilerbackup/mongodb-scheduler:0.0.1"
  imagePullPolicy: Always
  name: mongo-scheduler
  namespace: oiler-backup-system
  port: 50051
  replicas: 1
backuper:
  image: "oilerbackup/mongodb-backuper:0.0.1"
restorer:
  image: "oilerbackup/mongodb-restorer:0.0.1"